// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iR1-oOXE4js_E4SLMn9dz_eXM9bJJLw',
    appId: '1:597226831807:android:c1d72b2f78db14332dab0a',
    messagingSenderId: '597226831807',
    projectId: 'projectzed-115d7',
    storageBucket: 'projectzed-115d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsiHsXkhLaHWMCZ7MlDH62pEEQzzrukS0',
    appId: '1:597226831807:ios:15f24131f6ccae892dab0a',
    messagingSenderId: '597226831807',
    projectId: 'projectzed-115d7',
    storageBucket: 'projectzed-115d7.appspot.com',
    androidClientId: '597226831807-t2foq05besgp4d5iqf74t9sr4otcua1k.apps.googleusercontent.com',
    iosClientId: '597226831807-985d2bdge8lfj145ac8a2scpljh12frm.apps.googleusercontent.com',
    iosBundleId: 'com.project.zed',
  );
}
